### ISSUE TITLE
F claim in scoreboard

### ISSUE THREAD

**Issue by llPushkarSinghll** [FactionMaster/FactionMaster#17]
Maybe if u can make extension scoreboard like this
![125899864-88940cd6-319b-4ffb-8022-f5eb7bab30ab](https://user-images.githubusercontent.com/84075300/131951854-a9534209-7999-446a-b9ab-02d9b1c4f068.jpeg)

**Comment by ShockedPlot7560** [comment]
I will check, by using ScoreHUD ?

**Comment by llPushkarSinghll** [comment]
> I will check, by using ScoreHUD ?

Hmm, yeah

**Comment by llPushkarSinghll** [comment]
Closed 👀

**Comment by ShockedPlot7560** [comment]
I've registered it, it will come later while I develop the API
