### ISSUE TITLE
Crash about entity in an area

### ISSUE THREAD

**Issue by Willtom999** [FactionMaster/FactionMaster#49]
[Wed_Sep_15-22.09.39-UTC_2021.log](https://github.com/ShockedPlot7560/FactionMaster/files/7173553/Wed_Sep_15-22.09.39-UTC_2021.log)

**Comment by ShockedPlot7560** [comment]
Can you explain more, when it is happenned, why ? Because juste the crashdump is not enough

**Comment by Willtom999** [comment]
Bug /f home name

**Comment by Willtom999** [comment]
@ShockedPlot7560

**Comment by ShockedPlot7560** [comment]
Le crash ne semble pas venir de FactionMaster et he n'arrive pas à le reproduire.

**Comment by Willtom999** [comment]
?

**Comment by ShockedPlot7560** [comment]
Peut tu me dire qu'est ce qu'il y avait à cet endroit : entity / scoreboard ?
Si rien n'y étais de semblable, cela ne vient pas de FactionMaster mais d'une autre source à définir

**Comment by Willtom999** [comment]
ok
